# Generated by Django 2.1.7 on 2020-01-15 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdultsField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ChildrenTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('dateOfBirth', models.DateField()),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('length', models.IntegerField()),
                ('rating', models.FloatField()),
                ('description', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('datetime', models.DateTimeField()),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Hall')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='StudentsTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('name', models.CharField(max_length=200)),
                ('surename', models.CharField(max_length=200)),
                ('studentsNumber', models.CharField(max_length=200)),
                ('discount', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employeeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.EmployeeType'),
        ),
    ]
