# Generated by Django 2.1.7 on 2020-01-15 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmallCinemaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adultsfield',
            old_name='surename',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='childrenticket',
            old_name='surename',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='studentsticket',
            old_name='surename',
            new_name='surname',
        ),
    ]
