# Generated by Django 2.1.7 on 2020-01-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SmallCinemaApp', '0002_auto_20200115_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdultsTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('seat', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Showtime')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.IntegerField()),
                ('code', models.CharField(max_length=8)),
                ('showtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Showtime')),
            ],
        ),
        migrations.DeleteModel(
            name='AdultsField',
        ),
        migrations.AddField(
            model_name='childrenticket',
            name='showtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Showtime'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentsticket',
            name='showtime',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SmallCinemaApp.Showtime'),
            preserve_default=False,
        ),
    ]
