# Generated by Django 2.1.7 on 2020-01-15 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallCinemaApp', '0003_auto_20200115_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
