# Generated by Django 2.1.7 on 2020-01-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmallCinemaApp', '0006_studentsticket_seat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childrenticket',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentsticket',
            name='studentsNumber',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
